name: GitHub secrets related to production environment

on:
  workflow_dispatch:

jobs:
  production-deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com

    steps:
      - name: 'Print secret from environment'
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"

  testing-deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com

    steps:
      - name: 'Print secret from environment'
        run: |
          echo "APP_SECRET does not exist in testing environment so it will get it from the repository secrets"
          echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"          
