name: GitHub Secrets
# you need to add APP_SECRET using the repository setting.

on:
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"
          echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"

      - name: Print Secret as an environment variable
        run: |
          echo "APP_SECRET: $APP_SECRET"
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}

      - run: env